version: '3.7'
services:
  web:
    build: ./geekcatalog
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./geekcatalog/:/usr/src/geekcatalog/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password_for_DB
      - POSTGRES_DB=name_of_DB
volumes:
  postgres_data:
    
