# Generated by Django 2.2.3 on 2020-08-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название товара')),
                ('receipt_date', models.DateTimeField(auto_now_add=True, verbose_name='дата поступления')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена товара')),
                ('unit', models.CharField(max_length=64, verbose_name='единица измерения')),
                ('supplier', models.CharField(max_length=128, verbose_name='наименование поставщика')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
